#!/bin/sh
#
printf "\n"
printf "Use 'npcs' to list the philosophers\n"
printf "Use 'npcjournal -f <name>' to watch a philosopher\n"
printf "Use 'finger <name>' to inspect a philosopher\n"
printf "\n"
printf "Note: you will be disconnected after five minutes of inactivity\n"
