#!/bin/sh
if [ "$#" -lt 2 ]
then
	echo "Usage: ${0##*/} name 'Full Name' ['Comment' [project_file]]" >&2
	exit 64
fi
set -e
umask 022
adduser --disabled-password --shell /bin/bash --gecos "$2,,,,$3" "$1" 
getent group philosophers > /dev/null || addgroup philosophers
adduser "$1" philosophers
echo "|/usr/local/bin/mail-processor" > /home/"$1"/.forward
mkdir -p /home/"$1"/.config/systemd/user/default.target.wants
ln -sf /etc/systemd/user/select-seat.path /etc/systemd/user/select-seat.service /home/"$1"/.config/systemd/user/default.target.wants
loginctl enable-linger "$1"
if [ -z "$4" ]
then
    exit 0
fi
if [ -e "$4" ]
then
    chmod 0751 "/home/$1"
    install -o "$1" -g "$1" -m 0644 -T "$4" "/home/$1/.project"
fi
