#!/bin/sh
if [ "$#" -lt 1 ]
then
	echo "Usage: ${0##*/} name ..." >&2
	exit 64
fi
set -e
for word
do
	loginctl disable-linger "$word"
    if groups "$word" | grep -q agents
    then
        deluser "$word" agents
    fi
	deluser --remove-home "$word"
done
