name: Build Release

concurrency: deployment

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  mkosi-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@v24
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: mkosi
      - name: Rename SHA256
        run: mv philosophers.SHA256SUMS SHA256SUMS
      - name: Automatic Releases
        id: release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ github.token }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            philosophers.tar.xz
            philosophers.nspawn
            SHA256SUMS
